# Generated by Django 5.2.3 on 2025-07-14 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mobileNo', models.CharField(max_length=15)),
                ('requirements', models.CharField(max_length=600)),
                ('date_time', models.DateTimeField(default=datetime.datetime.today, verbose_name='Date')),
            ],
        ),
    ]
