# Generated by Django 5.2.3 on 2025-07-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_describtion', models.CharField(max_length=300)),
                ('product_link', models.CharField(max_length=500)),
            ],
        ),
    ]
