# Generated by Django 5.2.3 on 2025-07-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
